#!/usr/bin/env ruby
# coding: utf-8
require 'optparse'
require 'eustia'
require 'eustia/version'

options = { config_file: "./config.rb", bind: "0.0.0.0" }
required = [:config_file]

parser = OptionParser.new { |opts|
  opts.banner = "Usage: eustia [options]"
  opts.on('-c config', '[Required] Set config file (default = ./config.rb)') do |config_file|
    options[:config_file] = config_file
  end
  opts.on('-p port', '[Optional] Set port number (default = 4567)') do |port|
    options[:port] = port.to_i
  end
  opts.on('-o address', '[Optional] Set address to bind (default = 0.0.0.0)') do |addr|
    options[:bind] = addr
  end
  opts.on('-v', '--version') { puts "Eustia v#{Eustia::VERSION}"; exit(0) }
}

begin
  parser.parse(ARGV)
  for key in required
    raise OptionParser::MissingArgument.new("Missing argument: -c") unless options[key]
  end
rescue => e
  puts e.message
  puts opts.help
  exit(1)
end

require File.expand_path(options.delete(:config_file))

Eustia::Setup.execute(options)
